### ISSUE TITLE
Won't display?

### ISSUE THREAD

**Issue by LennyPhoenix** [carmelopellegrino/xfce4-i3-window-title-plugin#1]
Just shows an ellipsis, no title or anything:
![image](https://user-images.githubusercontent.com/57148878/128093886-c9265b91-c457-47dc-a90d-399154ac6594.png)
Plugin should be just to the right of the window icon.

**Comment by carmelopellegrino** [comment]
What are the items on the right? Is there a separator, maybe set to expand? If so, try removing it.

**Comment by LennyPhoenix** [comment]
Interestingly I just reinstalled the plugin to test it out again and it works perfectly, sorry to bother you :P

**Comment by carmelopellegrino** [comment]
no problem! To me it's actually a nice thing to see that other people are using my code.
